edition = "2021"
newline_style = "Unix"

fn_params_layout = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true

# unstable stuff
unstable_features = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
overflow_delimited_expr = true
