[package]
name = "vkez-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["tracing"]

[dependencies]
ash = { version = "0.37", features = ["linked"] }
tracing = { version = "0.1.37", optional = true }
vk-mem = { git = "https://github.com/gwihlidal/vk-mem-rs", version = "0.2.3" }
